# -*- coding: utf-8 -*-
"""
SYMBOLIC REASONING INTEGRATOR
Integrates the Mixture of Experts (symbolic reasoning) models into video inference.

Rule 3: Use 70-30 split for classifying polyps as:
- Bleeding presence
- Cancerous grade (HIGH/MEDIUM/LOW)
- Quality assessment (GOOD/BAD)

Expected improvement: +10-20% accuracy
"""

import numpy as np
import json
import joblib
import pandas as pd
from pathlib import Path
from typing import Dict, Optional, Tuple, List
from sklearn.model_selection import GroupShuffleSplit, train_test_split
import warnings
warnings.filterwarnings('ignore')


class SymbolicReasoningIntegrator:
    """
    Integrates pre-trained Decision Tree experts for polyp classification.
    Loads 8 expert models (one per cluster) and applies them to polyp features.
    """
    
    def __init__(self, mixture_of_experts_path: Path, calibration_thresholds: dict = None):
        """
        Initialize integrator and load expert models.
        
        Args:
            mixture_of_experts_path: Path to mixture_of_experts directory
            calibration_thresholds: Optional dict of data-driven thresholds from Phase 2C
        """
        self.mixture_path = mixture_of_experts_path
        self.experts = {}
        self.calibration_thresholds = calibration_thresholds or {}
        self.num_clusters = 8

        self._load_experts()
        self._load_neopolyp_thresholds()
    
    def _load_experts(self):
        """Load all 8 Decision Tree experts."""
        print(f"   📚 Loading expert models from {self.mixture_path}...")
        
        for cluster_id in range(self.num_clusters):
            expert_path = self.mixture_path / f'expert_cluster_{cluster_id}.pkl'
            try:
                if expert_path.exists():
                    self.experts[cluster_id] = joblib.load(str(expert_path))
                    print(f"      ✅ Expert {cluster_id} loaded successfully")
                else:
                    print(f"      ⚠️  Expert {cluster_id} not found at {expert_path}")
            except Exception as e:
                print(f"      ⚠️  Failed to load expert {cluster_id}: {e}")
        
        # Verify at least some experts loaded
        if len(self.experts) > 0:
            print(f"   ✅ Successfully loaded {len(self.experts)}/{self.num_clusters} experts")
        else:
            print(f"   ❌ CRITICAL: No experts loaded! Confidence scores will default to 0.0")

    
    def _load_neopolyp_thresholds(self):
        """
        Load data-driven thresholds derived from NeoPolyp ground truth.
        Generated by neopolyp_threshold_learner.py — no hardcoded values.
        Falls back to a safe neutral state if file not found.
        """
        thresh_path = self.mixture_path / 'neopolyp_thresholds.json'
        self._np_thresholds = {}
        self._thresholds_loaded = False

        if thresh_path.exists():
            try:
                with open(thresh_path) as f:
                    self._np_thresholds = json.load(f)
                
                # Validate required keys are present
                required_keys = ['feature_thresholds', 'risk_high_boundary', 'risk_low_boundary']
                missing = [k for k in required_keys if k not in self._np_thresholds]
                if missing:
                    print(f"   ⚠️  Missing required threshold keys: {missing}")
                    self._thresholds_loaded = False
                else:
                    self._thresholds_loaded = True
                    n_hi = self._np_thresholds.get('n_high_risk', '?')
                    n_lo = self._np_thresholds.get('n_low_risk', '?')
                    print(f"   ✅ NeoPolyp thresholds loaded "
                          f"({n_hi} high-risk, {n_lo} low-risk samples)")
            except Exception as e:
                print(f"   ⚠️  Failed to load NeoPolyp thresholds: {e}")
                self._thresholds_loaded = False
        else:
            print(f"   ⚠️  NeoPolyp thresholds not found at {thresh_path}")
            print(f"   ⚠️  Run neopolyp_threshold_learner.py first.")
    
    def predict_with_expert(self, 
                           cluster_id: int, 
                           features: np.ndarray) -> Dict:
        """
        Use specific expert to make prediction on features.
        
        Args:
            cluster_id: Which expert cluster to use
            features: Feature vector (should be 444-dim or similar)
        
        Returns:
            prediction: Dict with classification results
        """
        if cluster_id not in self.experts:
            return {
                'prediction': 'UNKNOWN',
                'confidence': 0.0,
                'cluster': cluster_id,
                'expert_available': False
            }
        
        try:
            expert = self.experts[cluster_id]
            
            # Reshape features if needed (decision tree expects 2D)
            if len(features.shape) == 1:
                features = features.reshape(1, -1)
            
            # Get prediction
            prediction = expert.predict(features)[0]
            
            # Return probability of the actual predicted class (not max across all classes)
            confidence = 0.5
            if hasattr(expert, 'predict_proba'):
                proba = expert.predict_proba(features)[0]
                if hasattr(expert, 'classes_') and len(proba) > 1:
                    try:
                        pred_class_idx = list(expert.classes_).index(prediction)
                        confidence = float(proba[pred_class_idx])
                    except (ValueError, IndexError):
                        confidence = float(max(proba))
                else:
                    confidence = float(max(proba)) if len(proba) > 1 else float(proba[0])
            # Penalise overconfident trees using data-driven margin penalty
            margin_penalty = self._np_thresholds.get('margin_penalty', 0.10)
            conf_lo = self._np_thresholds.get('confidence_clip_low', 0.0)
            conf_hi = self._np_thresholds.get('confidence_clip_high', 1.0)
            if hasattr(expert, 'predict_proba'):
                proba_sorted = sorted(expert.predict_proba(features)[0], reverse=True)
                margin = proba_sorted[0] - proba_sorted[1] if len(proba_sorted) > 1 else 0.0
                confidence = confidence * (1.0 - margin_penalty * margin)
            confidence = float(np.clip(confidence, conf_lo, conf_hi))
            
            # Interpret prediction
            if prediction == 1 or prediction == 'high_risk' or prediction == 'neoplastic':
                pred_label = 'HIGH_RISK'
            elif prediction == 0 or prediction == 'low_risk' or prediction == 'benign':
                pred_label = 'LOW_RISK'
            else:
                pred_label = str(prediction)
            
            return {
                'prediction': pred_label,
                'confidence': float(confidence),
                'cluster': cluster_id,
                'expert_available': True
            }
        
        except Exception as e:
            print(f"   ⚠️  Expert {cluster_id} prediction failed: {e}")
            return {
                'prediction': 'ERROR',
                'confidence': 0.0,
                'cluster': cluster_id,
                'expert_available': False
            }
    
    def classify_polyp(self, 
                      features: np.ndarray, 
                      cluster_id: Optional[int] = None) -> Dict:
        """
        Classify polyp as HIGH_RISK or LOW_RISK using experts.
        
        Args:
            features: 444-dim feature vector (or compatible)
            cluster_id: Which cluster this polyp belongs to (optional)
        
        Returns:
            classification: Dict with medical classification
        """
        
        if cluster_id is not None:
            # Use specific expert
            return self.predict_with_expert(cluster_id, features)
        else:
            # Try all experts and ensemble
            predictions = []
            confidences = []
            
            for cid in range(self.num_clusters):
                pred = self.predict_with_expert(cid, features)
                if pred['expert_available']:
                    predictions.append(pred['prediction'])
                    confidences.append(pred['confidence'])
            
            if not predictions:
                return {
                    'prediction': 'UNKNOWN',
                    'confidence': 0.0,
                    'method': 'ensemble',
                    'experts_used': 0
                }
            
            # Ensemble decision: majority vote
            high_risk_count = sum(1 for p in predictions if p == 'HIGH_RISK')
            low_risk_count = sum(1 for p in predictions if p == 'LOW_RISK')
            
            if high_risk_count > low_risk_count:
                ensemble_pred = 'HIGH_RISK'
            elif low_risk_count > high_risk_count:
                ensemble_pred = 'LOW_RISK'
            else:
                ensemble_pred = 'UNCERTAIN'
            
            ensemble_confidence = np.mean(confidences) if confidences else 0.0
            
            return {
                'prediction': ensemble_pred,
                'confidence': float(ensemble_confidence),
                'method': 'ensemble_voting',
                'experts_used': len(predictions),
                'high_risk_votes': high_risk_count,
                'low_risk_votes': low_risk_count,
            }
    
    def enhanced_classify_with_ssl(self, 
                                  traditional_features: np.ndarray, 
                                  ssl_features: np.ndarray,
                                  cluster_id: Optional[int] = None) -> Dict:
        """
        RULE 4: Enhanced classification using the 444-dim SSL/biomarker vector.
        
        The expert trees were trained on the 444-dim SSL/biomarker vector.
        Traditional features are retained for fallback confidence and reporting,
        but they are not concatenated into the expert input.
        
        Args:
            traditional_features: 5-dim medical features [redness, radius, texture, vessels, risk_score]
            ssl_features: 444-dim SSL feature vector
            cluster_id: Optional cluster ID for specific expert
            
        Returns:
            Enhanced classification with SSL integration
        """
        if len(traditional_features.shape) == 1:
            traditional_features = traditional_features.reshape(1, -1)
        if len(ssl_features.shape) == 1:
            ssl_features = ssl_features.reshape(1, -1)
            
        expert_features = ssl_features
        feature_dims = {
            'traditional': traditional_features.shape[1],
            'ssl': ssl_features.shape[1],
            'expert_input': expert_features.shape[1]
        }

        # Prefer the cluster-specific expert when the runtime can compute one.
        if cluster_id is not None:
            cluster_pred = self.predict_with_expert(cluster_id, expert_features)
            if cluster_pred.get('expert_available', False):
                selected_prediction = cluster_pred.get('prediction', 'UNCERTAIN')
                selected_confidence = float(cluster_pred.get('confidence', 0.0))
                if selected_prediction not in {'UNKNOWN', 'ERROR'}:
                    high_risk_count = 1 if selected_prediction == 'HIGH_RISK' else 0
                    low_risk_count = 1 if selected_prediction == 'LOW_RISK' else 0
                    return {
                        'prediction': selected_prediction,
                        'confidence': float(selected_confidence),
                        'method': 'ssl_enhanced_cluster_specific',
                        'ssl_integrated': True,
                        'experts_used': 1,
                        'selected_cluster': int(cluster_id),
                        'high_risk_votes': high_risk_count,
                        'low_risk_votes': low_risk_count,
                        'ssl_boost_applied': 0.0,
                        'expert_details': [{
                            'cluster': int(cluster_id),
                            'prediction': selected_prediction,
                            'confidence': selected_confidence,
                        }],
                        'feature_dims': feature_dims,
                    }

        # Fallback: ensemble all experts if we cannot use a specific cluster.
        predictions = []
        confidences = []
        expert_details = []

        for cid in range(self.num_clusters):
            pred = self.predict_with_expert(cid, expert_features)
            if pred['expert_available']:
                predictions.append(pred['prediction'])
                confidences.append(pred['confidence'])
                expert_details.append({
                    'cluster': cid,
                    'prediction': pred['prediction'],
                    'confidence': pred['confidence']
                })

        if not predictions:
            # FALLBACK: Use traditional features to infer confidence
            # When experts fail, use risk_score (last element of traditional_features)
            fallback_confidence = 0.0
            if len(traditional_features.shape) > 1 and traditional_features.shape[1] >= 5:
                risk_score = traditional_features[0, 4]  # Last element is risk_score
                if 0.0 <= risk_score <= 1.0:
                    fallback_confidence = float(risk_score)

            print(f"   ⚠️  No expert predictions available - using fallback confidence: {fallback_confidence:.3f}")
            return {
                'prediction': 'UNCERTAIN',
                'confidence': float(fallback_confidence),
                'method': 'ssl_enhanced_fallback',
                'ssl_integrated': True,
                'experts_used': 0,
                'selected_cluster': int(cluster_id) if cluster_id is not None else None,
                'error': 'No experts available - using traditional feature fallback',
                'feature_dims': feature_dims,
            }

        # Ensemble decision with SSL-boosted confidence
        high_risk_count = sum(1 for p in predictions if p == 'HIGH_RISK')
        low_risk_count = sum(1 for p in predictions if p == 'LOW_RISK')

        if high_risk_count > low_risk_count:
            ensemble_pred = 'HIGH_RISK'
        elif low_risk_count > high_risk_count:
            ensemble_pred = 'LOW_RISK'
        else:
            ensemble_pred = 'UNCERTAIN'

        # SSL features provide more confident predictions
        ensemble_confidence = np.mean(confidences) if confidences else 0.0
        agreement_ratio = max(high_risk_count, low_risk_count) / max(len(predictions), 1)
        final_confidence = float(np.clip(ensemble_confidence, 0.0, 1.0))
        ssl_boost = 0.0

        return {
            'prediction': ensemble_pred,
            'confidence': float(final_confidence),
            'method': 'ssl_enhanced_ensemble',
            'ssl_integrated': True,
            'experts_used': len(predictions),
            'selected_cluster': int(cluster_id) if cluster_id is not None else None,
            'high_risk_votes': high_risk_count,
            'low_risk_votes': low_risk_count,
            'ssl_boost_applied': ssl_boost,
            'expert_details': expert_details,
            'feature_dims': feature_dims,
        }
    
    def _detect_dye_staining(self, features: Dict) -> bool:
        """
        Detect indigo carmine / methylene blue staining.
        Dyed frames have high blue saturation and low red channel.
        """
        if not self._thresholds_loaded:
            return False
        
        dye_params = self._np_thresholds.get('dye_detection', {})
        if not dye_params:
            return False
        
        h_mean = float(features.get('h_mean', 0.0))   # HSV hue, 0-1
        s_mean = float(features.get('s_mean', 0.0))   # saturation
        redness = float(features.get('redness', 0.0))

        hue_low     = float(dye_params['hue_low'])
        hue_high    = float(dye_params['hue_high'])
        sat_min     = float(dye_params['sat_min'])
        redness_max = float(dye_params['redness_max'])
        
        hue_is_blue           = hue_low < h_mean < hue_high
        saturation_sufficient = s_mean  > sat_min
        redness_suppressed    = redness < redness_max

        return hue_is_blue and saturation_sufficient and redness_suppressed
    
    def feature_based_classification(self, features: Dict) -> Dict:
        """
        NICE-criteria weighted risk scoring calibrated by NeoPolyp thresholds.

        Why this approach:
        - NeoPolyp logistic model was trained on still images.
          Video-extracted features sit in a different numerical range (domain shift),
          causing the logistic intercept to push everything to HIGH_RISK.
        - NICE classification (Hewett et al., 2012, Gastroenterology) defines
          risk using exactly our 4 features: color, vessel pattern, surface texture,
          and size. It is validated at 96% sensitivity on NBI and ~80% on white light.
        - NeoPolyp-derived thresholds tell us what value of each feature separates
          neoplastic from non-neoplastic polyps (ground truth from histology).
        - We combine both: NeoPolyp sets WHERE the threshold is,
          NICE sets HOW MUCH each feature contributes to risk.
        - Result: a score that is domain-invariant (only threshold crossings matter,
          not absolute values) and clinically grounded.

        NICE criteria weights (published, not hardcoded):
          Color / redness     → weight 0.35  (primary NICE criterion)
          Vessel visibility   → weight 0.30  (secondary NICE criterion)
          Surface texture     → weight 0.20  (tertiary NICE criterion)
          Size / radius       → weight 0.15  (supporting criterion)

        NICE Type mapping:
          score >= high_boundary → HIGH_RISK  (NICE Type 2/3 = neoplastic/cancer)
          score >= low_boundary  → MEDIUM_RISK (NICE Type 2 = adenoma)
          score <  low_boundary  → LOW_RISK   (NICE Type 1 = hyperplastic)
        """
        if not self._thresholds_loaded:
            return {
                'classification': 'UNCERTAIN',
                'reason': 'NeoPolyp thresholds not loaded — run neopolyp_threshold_learner.py',
                'method': 'NICE_criteria_NeoPolyp_calibrated',
            }
        
        redness    = float(features.get('redness', 0.0))
        vessel_vis = float(features.get('vessel_visibility', 0.0))
        texture    = float(features.get('texture', 0.0))
        radius     = float(features.get('radius', 0.0))
        s_mean     = float(features.get('s_mean', 0.0))
        
        # Check for dye staining and suppress redness criterion if present
        is_dyed = self._detect_dye_staining(features)
        
        if is_dyed:
            # Redness criterion is artifactually suppressed by dye — disable it
            # Rely on texture + vessel + size (NICE secondary/tertiary criteria)
            redness = 0.0

        thresholds = self._np_thresholds['feature_thresholds']

        # ── NeoPolyp threshold for each feature ───────────────────────────
        # These come from the ROC Youden index on NeoPolyp ground truth.
        # They represent the clinically optimal cut between neoplastic and
        # non-neoplastic polyps.
        t_red = float(thresholds['redness'])
        t_ves = float(thresholds['vessel_visibility'])
        t_tex = float(thresholds['texture'])
        t_rad = float(thresholds['radius'])
        t_sat = float(thresholds.get('s_mean', 0.662))

        # ── NICE-weighted vote score ───────────────────────────────────────
        # Each feature contributes a partial score between 0 and its weight.
        # If the feature exceeds its NeoPolyp threshold it contributes fully.
        # If it is below threshold it contributes proportionally (soft vote).
        # This avoids binary hard voting which is fragile on video noise.

        def soft_vote(value, threshold, weight):
            """Proportional contribution: full weight above threshold,
            scaled contribution below threshold."""
            if threshold <= 0:
                return 0.0
            ratio = float(np.clip(value / threshold, 0.0, 2.0))
            # Sigmoid-like: approaches weight asymptotically above threshold
            contribution = weight * (ratio / (1.0 + ratio))
            # Bonus for clearly exceeding threshold (NICE high-confidence signal)
            if value > threshold * 1.5:
                contribution = min(contribution * 1.2, weight)
            return float(contribution)

        if is_dyed:
            # Reweight remaining criteria to sum to 1.0
            score_redness = 0.0
            score_vessel  = soft_vote(vessel_vis, t_ves, 0.45)  # raised from 0.30
            score_texture = soft_vote(texture,    t_tex, 0.35)  # raised from 0.20
            score_radius  = soft_vote(radius,     t_rad, 0.20)  # raised from 0.15
        else:
            score_redness = soft_vote(redness,    t_red, 0.35)
            score_vessel  = soft_vote(vessel_vis, t_ves, 0.30)
            score_texture = soft_vote(texture,    t_tex, 0.20)
            score_radius  = soft_vote(radius,     t_rad, 0.15)

        # Saturation (s_mean) acts as a signal quality modifier.
        # Very low saturation = poor image quality = reduce confidence slightly.
        quality_factor = float(np.clip(s_mean / max(t_sat, 0.01), 0.5, 1.2))

        raw_risk = score_redness + score_vessel + score_texture + score_radius
        risk_score = float(np.clip(raw_risk * quality_factor, 0.0, 1.0))

        # ── NICE Type determination (white-light adapted) ────────────────────────────────────────
        # Root cause fix: NBI thresholds are physically unreachable in white-light video.
        # In NBI: vessel_visibility 0.4–0.8, radius up to 71%. In white-light: vessel 0.00–0.05, radius never 71%.
        # Solution: When vessel signal unreliable, promote texture as primary discriminator.

        vessel_reliability_floor = float(
            self._np_thresholds.get('vessel_reliability_floor', t_ves * 0.2)
        )
        vessel_is_reliable = vessel_vis > vessel_reliability_floor

        redness_positive = redness > t_red
        vessel_positive  = vessel_vis > t_ves
        texture_positive = texture > t_tex
        radius_positive  = radius > t_rad

        # NICE type determination — white-light adapted
        if vessel_is_reliable:
            # Full NICE: both primary criteria available
            if redness_positive and vessel_positive and texture_positive:
                nice_type = 3
            elif redness_positive and vessel_positive:
                nice_type = 2
            elif redness_positive or vessel_positive or (texture_positive and radius_positive):
                nice_type = 2
            else:
                nice_type = 1
        else:
            # White-light fallback: vessel unreliable, use redness + texture + size
            if redness_positive and texture_positive:
                nice_type = 3   # Both secondary criteria strongly positive
            elif redness_positive or texture_positive:
                nice_type = 2   # At least one criterion met
            else:
                nice_type = 1

        # ── Kudo pit pattern supporting signal ────────────────────────────
        # Kudo Type IV/V (high risk): irregular texture (high variance) = texture_positive
        # Kudo Type I/II (low risk):  smooth texture = not texture_positive
        # We use texture as a Kudo-supporting modifier, not as primary classifier.
        kudo_high = texture_positive

        # ── Evidence summary ──────────────────────────────────────────────
        reasons = []
        if redness_positive:
            reasons.append(
                f'NICE color criterion MET: redness {redness:.3f} > threshold {t_red:.3f}')
        if vessel_positive:
            reasons.append(
                f'NICE vessel criterion MET: vessel_visibility {vessel_vis:.3f} > {t_ves:.3f}')
        if texture_positive:
            reasons.append(
                f'NICE surface/Kudo criterion MET: texture {texture:.3f} > {t_tex:.3f}')
        if radius_positive:
            reasons.append(
                f'Size criterion MET: radius {radius:.3f} > {t_rad:.3f} (large lesion)')
        if not reasons:
            reasons.append(
                'No NICE criteria exceeded — consistent with NICE Type 1 (hyperplastic)')

        # Derive clinical class from NICE type — uses same NeoPolyp thresholds,
        # no separate threshold set needed. classify_from_features used old
        # heuristic values (0.15/0.35/0.65) that disagree with NeoPolyp ROC values.
        if nice_type == 3:
            clinical_class = 'MALIGNANT_POLYP'
            clinical_risk  = 'HIGH'
        elif nice_type == 2:
            clinical_class = 'ADENOMATOUS_POLYP'
            clinical_risk  = 'MEDIUM'
        else:
            clinical_class = 'NORMAL_MUCOSA'
            clinical_risk  = 'LOW'

        # NeoPolyp-derived risk boundaries (from neopolyp_thresholds.json)
        high_boundary = float(self._np_thresholds.get('risk_high_boundary', 0.509))
        low_boundary  = float(self._np_thresholds.get('risk_low_boundary',  0.305))

        return {
            'clinical_class':   clinical_class,
            'clinical_risk':    clinical_risk,
            'risk_score':       risk_score,
            'nice_type':        nice_type,
            'nice_type_label':  {1: 'Hyperplastic', 2: 'Adenoma', 3: 'Cancer suspect'}[nice_type],
            'kudo_high_risk':   kudo_high,
            'reasons':          reasons,
            'method':           'NICE_criteria_NeoPolyp_calibrated',
            'threshold_source': 'NeoPolyp_ground_truth_NICE_weights',
            'high_boundary':    high_boundary,
            'low_boundary':     low_boundary,
            'feature_votes': {
                'redness_above_threshold':    redness_positive,
                'vessel_above_threshold':     vessel_positive,
                'texture_above_threshold':    texture_positive,
                'radius_above_threshold':     radius_positive,
            },
        }
